# Generated by Django 6.0.3 on 2026-05-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('STAFF', 'STAFF'), ('INVENTORY MANAGER', 'INVENTORY MANAGER')], default='STAFF', max_length=30),
        ),
    ]
