# Generated by Django 6.0.3 on 2026-05-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('OUT_OF_STOCK', 'Out Of Stock'), ('ORDER_CREATED', 'Order Created'), ('ORDER_COMPLETED', 'Order Completed'), ('NEW_PRODUCT', 'New Product'), ('STOCK_IN', 'Stock In'), ('STOCK_OUT', 'Stock Out')], max_length=50),
        ),
    ]
